### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [donmaiq/mpv-filenavigator#10]
Hi there,

I'm currently working on a Arch Linux distribution package for the [AUR](https://aur.archlinux.org/) and noticed you haven't specified what license this and [your other scripts](https://github.com/jonniek/mpv-scripts) are distributed under.

This is of course not mandatory, but providing licensing information would be very helpful for people like me to know what terms, if any, your code can be distributed under. 

If you've got some spare time I'd really appreciate it if you could [pick out a license](https://choosealicense.com/licenses/)<sup>1</sup>. Or, if you don't fancy any of these open source licenses, if you can let me know here whether I can distribute this package and under what terms.

Sincerely,
Joost

<sup>1: TL;DR, if you're okay with just about anything the [MIT](https://choosealicense.com/licenses/mit/) license is probably for you.</sup>

**Comment by jonniek** [comment]
Thanks for the issue. I added license information on my mpv scripts that were still missing it.

**Comment by MadeOfMagicAndWires** [comment]
Cheers!

**Comment by MadeOfMagicAndWires** [comment]
AUR package can be found [here](https://aur.archlinux.org/packages/mpv-filenavigator-git/)
