### ISSUE TITLE
Subtitle support

### ISSUE THREAD

**Issue by smhmd** [donmaiq/mpv-filenavigator#11]
I could not find a decent subtitle opener on Linux (happy to be recommended one), and this is the best implementation for folder navigation IMO, so, could you make it so nav-open a subtitles file add and activate the sub, nav-forward to add sub to the subs on current playing video?

**Comment by jonniek** [comment]
Sounds like a good feature. I will try implementing this soon.

**Comment by smhmd** [comment]
Also, I would suggest allowing external configuration of the script in the configuration folder mpv recommends. I always have to reenter my configuration (in filenav's case, I changed keybindings, favorites, and timeout) whenever a new version of the scripts drops. also, add versioning or time, so one knows when their script is out of date.

**EDIT**: I just use `git pull rebase`, nowadays.

**Comment by jonniek** [comment]
Added basic subtitle support 7f97fd7eae8fa5e00895cc217e1836f7f44677b2

I'm still looking into how to "append" the sub, currently it seems to select the new loaded sub. So `navopen` and `navforward` work currently the same way, only difference is that `navforward` keeps the navigator open.

**Comment by shabahengam** [comment]
I think you should add `ass` format to `subtitleformats` list.

**Comment by jonniek** [comment]
Fixed c11894a71bc6a9b69ab37dae8eb00c0067c65a0f

**Comment by smhmd** [comment]
@jonniek `lrc` too.

**Comment by jonniek** [comment]
>Also, I would suggest allowing external configuration of the script in the configuration folder mpv recommends

This should be already possible. However, table variables can not be passed in. I added another issue for that https://github.com/jonniek/mpv-filenavigator/issues/16
