### ISSUE TITLE
Esc to close navigator

### ISSUE THREAD

**Issue by smhmd** [donmaiq/mpv-filenavigator#12]
`esc/navigator_mainkey` to close navigator. Currently, you have to wait for the script to timeout when adding to playlist.

**Comment by jonniek** [comment]
Sorry I didn't notice this issue. You can enable toggle visibility by changing `menu_timeout = false`. Then you can close it with the same key as opening.

I think I will change this to the default behavior soon.

**Comment by jonniek** [comment]
Done 6a0d855ded6ed438e595cdaedff007f46849da8f
