### ISSUE TITLE
can't use arrow keys to backward or forward

### ISSUE THREAD

**Issue by shabahengam** [donmaiq/mpv-filenavigator#15]
hi.first of all thanks for this great script.
after this commit 6a0d855 when I select a file with Enter I can't use arrowkeys to backward or forward because every time I press RIGHT  the navigation menu pop up and say *Appended file to playlist* and when i press LEFT it goes back to parent directory.i do **not** need a playlist manager i just want navigate through my files and play them.i reverted that commit (on my system) because right now this script is unusable,IMO.

**Comment by jonniek** [comment]
Thanks for the bug report. Removal of dynamic keybinds was broken because of some name refactoring. I have fixed the issue on 3d8d6b772e74bf22644872f52cde1e0772120440

**Comment by shabahengam** [comment]
thanks again for this great script.i close the issue.
