### ISSUE TITLE
Todo UI & UX features

### ISSUE THREAD

**Issue by jonniek** [donmaiq/mpv-filenavigator#6]
Anyone is free to contribute:

-  Create option to toggle visibility instead of relying on timeout. See [playlistmanager](https://github.com/jonniek/mpv-playlistmanager) for reference.
-  Use assdraw with user defined styles instead of osd message. See [playlistmanager](https://github.com/jonniek/mpv-playlistmanager) for reference.
-  Add option to make font scale by window size. See [playlistmanager](https://github.com/jonniek/mpv-playlistmanager) for reference.
-  Use similar utf characters as [playlistmanger](https://github.com/jonniek/mpv-playlistmanager) for selection visuals
-  Rethink the add / remove to playlist flow as now it is quite clunky and unreliable

**Comment by zamanisaja** [comment]
I wrote a script for the same purpose a long time ago! [link](https://github.com/zamanisaja/dotfiles/commit/be0f14e4342584e5c81d79de098ede0caba1760a#diff-bde5f5295fa0b82bf281597eabb37cf1) but not as neat as yours!
It was supposed to be both navigator and playlist manager.
Interestingly our naming patterns are very much alike! 
I'm hoping to steal some ideas from yours :)
